/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickListRouteImport } from './routes/pick-list'
import { Route as BoxesRouteImport } from './routes/boxes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoxesBoxIdRouteImport } from './routes/boxes.$boxId'
import { Route as BoxesBoxIdScanRouteImport } from './routes/boxes.$boxId.scan'

const PickListRoute = PickListRouteImport.update({
  id: '/pick-list',
  path: '/pick-list',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesRoute = BoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBoxIdRoute = BoxesBoxIdRouteImport.update({
  id: '/$boxId',
  path: '/$boxId',
  getParentRoute: () => BoxesRoute,
} as any)
const BoxesBoxIdScanRoute = BoxesBoxIdScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => BoxesBoxIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/pick-list': typeof PickListRoute
  '/boxes/$boxId': typeof BoxesBoxIdRouteWithChildren
  '/boxes/$boxId/scan': typeof BoxesBoxIdScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/pick-list': typeof PickListRoute
  '/boxes/$boxId': typeof BoxesBoxIdRouteWithChildren
  '/boxes/$boxId/scan': typeof BoxesBoxIdScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/pick-list': typeof PickListRoute
  '/boxes/$boxId': typeof BoxesBoxIdRouteWithChildren
  '/boxes/$boxId/scan': typeof BoxesBoxIdScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boxes'
    | '/pick-list'
    | '/boxes/$boxId'
    | '/boxes/$boxId/scan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boxes' | '/pick-list' | '/boxes/$boxId' | '/boxes/$boxId/scan'
  id:
    | '__root__'
    | '/'
    | '/boxes'
    | '/pick-list'
    | '/boxes/$boxId'
    | '/boxes/$boxId/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxesRoute: typeof BoxesRouteWithChildren
  PickListRoute: typeof PickListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pick-list': {
      id: '/pick-list'
      path: '/pick-list'
      fullPath: '/pick-list'
      preLoaderRoute: typeof PickListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes': {
      id: '/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof BoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$boxId': {
      id: '/boxes/$boxId'
      path: '/$boxId'
      fullPath: '/boxes/$boxId'
      preLoaderRoute: typeof BoxesBoxIdRouteImport
      parentRoute: typeof BoxesRoute
    }
    '/boxes/$boxId/scan': {
      id: '/boxes/$boxId/scan'
      path: '/scan'
      fullPath: '/boxes/$boxId/scan'
      preLoaderRoute: typeof BoxesBoxIdScanRouteImport
      parentRoute: typeof BoxesBoxIdRoute
    }
  }
}

interface BoxesBoxIdRouteChildren {
  BoxesBoxIdScanRoute: typeof BoxesBoxIdScanRoute
}

const BoxesBoxIdRouteChildren: BoxesBoxIdRouteChildren = {
  BoxesBoxIdScanRoute: BoxesBoxIdScanRoute,
}

const BoxesBoxIdRouteWithChildren = BoxesBoxIdRoute._addFileChildren(
  BoxesBoxIdRouteChildren,
)

interface BoxesRouteChildren {
  BoxesBoxIdRoute: typeof BoxesBoxIdRouteWithChildren
}

const BoxesRouteChildren: BoxesRouteChildren = {
  BoxesBoxIdRoute: BoxesBoxIdRouteWithChildren,
}

const BoxesRouteWithChildren = BoxesRoute._addFileChildren(BoxesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxesRoute: BoxesRouteWithChildren,
  PickListRoute: PickListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
