/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickListsRouteImport } from './routes/pick-lists'
import { Route as PickListRouteImport } from './routes/pick-list'
import { Route as BoxesRouteImport } from './routes/boxes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickListsIndexRouteImport } from './routes/pick-lists.index'
import { Route as BoxesIndexRouteImport } from './routes/boxes.index'
import { Route as PickListsPickListIdRouteImport } from './routes/pick-lists.$pickListId'
import { Route as BoxesBoxIdRouteImport } from './routes/boxes.$boxId'
import { Route as ApiDelverWebhookRouteImport } from './routes/api.delver-webhook'
import { Route as ApiDelverPollRouteImport } from './routes/api.delver-poll'
import { Route as BoxesBoxIdScanRouteImport } from './routes/boxes.$boxId.scan'

const PickListsRoute = PickListsRouteImport.update({
  id: '/pick-lists',
  path: '/pick-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const PickListRoute = PickListRouteImport.update({
  id: '/pick-list',
  path: '/pick-list',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesRoute = BoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickListsIndexRoute = PickListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PickListsRoute,
} as any)
const BoxesIndexRoute = BoxesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoxesRoute,
} as any)
const PickListsPickListIdRoute = PickListsPickListIdRouteImport.update({
  id: '/$pickListId',
  path: '/$pickListId',
  getParentRoute: () => PickListsRoute,
} as any)
const BoxesBoxIdRoute = BoxesBoxIdRouteImport.update({
  id: '/$boxId',
  path: '/$boxId',
  getParentRoute: () => BoxesRoute,
} as any)
const ApiDelverWebhookRoute = ApiDelverWebhookRouteImport.update({
  id: '/api/delver-webhook',
  path: '/api/delver-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDelverPollRoute = ApiDelverPollRouteImport.update({
  id: '/api/delver-poll',
  path: '/api/delver-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBoxIdScanRoute = BoxesBoxIdScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => BoxesBoxIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/pick-list': typeof PickListRoute
  '/pick-lists': typeof PickListsRouteWithChildren
  '/api/delver-poll': typeof ApiDelverPollRoute
  '/api/delver-webhook': typeof ApiDelverWebhookRoute
  '/boxes/$boxId': typeof BoxesBoxIdRouteWithChildren
  '/pick-lists/$pickListId': typeof PickListsPickListIdRoute
  '/boxes/': typeof BoxesIndexRoute
  '/pick-lists/': typeof PickListsIndexRoute
  '/boxes/$boxId/scan': typeof BoxesBoxIdScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pick-list': typeof PickListRoute
  '/api/delver-poll': typeof ApiDelverPollRoute
  '/api/delver-webhook': typeof ApiDelverWebhookRoute
  '/boxes/$boxId': typeof BoxesBoxIdRouteWithChildren
  '/pick-lists/$pickListId': typeof PickListsPickListIdRoute
  '/boxes': typeof BoxesIndexRoute
  '/pick-lists': typeof PickListsIndexRoute
  '/boxes/$boxId/scan': typeof BoxesBoxIdScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/pick-list': typeof PickListRoute
  '/pick-lists': typeof PickListsRouteWithChildren
  '/api/delver-poll': typeof ApiDelverPollRoute
  '/api/delver-webhook': typeof ApiDelverWebhookRoute
  '/boxes/$boxId': typeof BoxesBoxIdRouteWithChildren
  '/pick-lists/$pickListId': typeof PickListsPickListIdRoute
  '/boxes/': typeof BoxesIndexRoute
  '/pick-lists/': typeof PickListsIndexRoute
  '/boxes/$boxId/scan': typeof BoxesBoxIdScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boxes'
    | '/pick-list'
    | '/pick-lists'
    | '/api/delver-poll'
    | '/api/delver-webhook'
    | '/boxes/$boxId'
    | '/pick-lists/$pickListId'
    | '/boxes/'
    | '/pick-lists/'
    | '/boxes/$boxId/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pick-list'
    | '/api/delver-poll'
    | '/api/delver-webhook'
    | '/boxes/$boxId'
    | '/pick-lists/$pickListId'
    | '/boxes'
    | '/pick-lists'
    | '/boxes/$boxId/scan'
  id:
    | '__root__'
    | '/'
    | '/boxes'
    | '/pick-list'
    | '/pick-lists'
    | '/api/delver-poll'
    | '/api/delver-webhook'
    | '/boxes/$boxId'
    | '/pick-lists/$pickListId'
    | '/boxes/'
    | '/pick-lists/'
    | '/boxes/$boxId/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxesRoute: typeof BoxesRouteWithChildren
  PickListRoute: typeof PickListRoute
  PickListsRoute: typeof PickListsRouteWithChildren
  ApiDelverPollRoute: typeof ApiDelverPollRoute
  ApiDelverWebhookRoute: typeof ApiDelverWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pick-lists': {
      id: '/pick-lists'
      path: '/pick-lists'
      fullPath: '/pick-lists'
      preLoaderRoute: typeof PickListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-list': {
      id: '/pick-list'
      path: '/pick-list'
      fullPath: '/pick-list'
      preLoaderRoute: typeof PickListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes': {
      id: '/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof BoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-lists/': {
      id: '/pick-lists/'
      path: '/'
      fullPath: '/pick-lists/'
      preLoaderRoute: typeof PickListsIndexRouteImport
      parentRoute: typeof PickListsRoute
    }
    '/boxes/': {
      id: '/boxes/'
      path: '/'
      fullPath: '/boxes/'
      preLoaderRoute: typeof BoxesIndexRouteImport
      parentRoute: typeof BoxesRoute
    }
    '/pick-lists/$pickListId': {
      id: '/pick-lists/$pickListId'
      path: '/$pickListId'
      fullPath: '/pick-lists/$pickListId'
      preLoaderRoute: typeof PickListsPickListIdRouteImport
      parentRoute: typeof PickListsRoute
    }
    '/boxes/$boxId': {
      id: '/boxes/$boxId'
      path: '/$boxId'
      fullPath: '/boxes/$boxId'
      preLoaderRoute: typeof BoxesBoxIdRouteImport
      parentRoute: typeof BoxesRoute
    }
    '/api/delver-webhook': {
      id: '/api/delver-webhook'
      path: '/api/delver-webhook'
      fullPath: '/api/delver-webhook'
      preLoaderRoute: typeof ApiDelverWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delver-poll': {
      id: '/api/delver-poll'
      path: '/api/delver-poll'
      fullPath: '/api/delver-poll'
      preLoaderRoute: typeof ApiDelverPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$boxId/scan': {
      id: '/boxes/$boxId/scan'
      path: '/scan'
      fullPath: '/boxes/$boxId/scan'
      preLoaderRoute: typeof BoxesBoxIdScanRouteImport
      parentRoute: typeof BoxesBoxIdRoute
    }
  }
}

interface BoxesBoxIdRouteChildren {
  BoxesBoxIdScanRoute: typeof BoxesBoxIdScanRoute
}

const BoxesBoxIdRouteChildren: BoxesBoxIdRouteChildren = {
  BoxesBoxIdScanRoute: BoxesBoxIdScanRoute,
}

const BoxesBoxIdRouteWithChildren = BoxesBoxIdRoute._addFileChildren(
  BoxesBoxIdRouteChildren,
)

interface BoxesRouteChildren {
  BoxesBoxIdRoute: typeof BoxesBoxIdRouteWithChildren
  BoxesIndexRoute: typeof BoxesIndexRoute
}

const BoxesRouteChildren: BoxesRouteChildren = {
  BoxesBoxIdRoute: BoxesBoxIdRouteWithChildren,
  BoxesIndexRoute: BoxesIndexRoute,
}

const BoxesRouteWithChildren = BoxesRoute._addFileChildren(BoxesRouteChildren)

interface PickListsRouteChildren {
  PickListsPickListIdRoute: typeof PickListsPickListIdRoute
  PickListsIndexRoute: typeof PickListsIndexRoute
}

const PickListsRouteChildren: PickListsRouteChildren = {
  PickListsPickListIdRoute: PickListsPickListIdRoute,
  PickListsIndexRoute: PickListsIndexRoute,
}

const PickListsRouteWithChildren = PickListsRoute._addFileChildren(
  PickListsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxesRoute: BoxesRouteWithChildren,
  PickListRoute: PickListRoute,
  PickListsRoute: PickListsRouteWithChildren,
  ApiDelverPollRoute: ApiDelverPollRoute,
  ApiDelverWebhookRoute: ApiDelverWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
